image:
  file: .gitpod/.gitpod.Dockerfile

tasks:
  - init: >
      composer install &&
      mysql -e 'create database homestead' &&
      php artisan migrate
    command: php artisan serve

ports:
  - port: 8000
    onOpen: open-preview
  - port: 3306
    onOpen: ignore
